image: node:14

pages:
  cache:
    paths:
      - node_modules/
  script:
    # Specify the steps involved to build your app here
    - yarn install
    - yarn build

  artifacts:
    paths:
      - public

  only:
    # Trigger a new build and deploy only when there is a push to the
    # branch(es) below
    - latest
