image: node:12.20.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - BUILD_GITLAB=true npm run build
    - rm -rf ./public/* && cp -r ./dist/* ./public
  artifacts:
    paths:
      - public
  only:
    - latest
